<div class="page">
      <div class="page-main">
          <div class="page-content">
              <div class="container">
                <div class="row row-cards row-deck">
                    <div class="col-12">
                    <div class="card update_series_wrapper" id="generated_numbers">
                      <div class="card-header">
                        <h3 class="card-title">History</h3>
                      </div>
                      <div class="table-responsive">
                        <table class="table card-table table-vcenter text-nowrap">
                        <?php if(count($history) > 0){?>
                          <thead>
                            <tr>
                              <th class="w-1">No.</th>
                              <th>Total Numbers</th>
                              <th>Start Number</th>
                              <th>End Number</th>
                              <th>Generated By</th>
                              <th>Data Source</th>
                              <th>Date Added</th>
                              <th>Detail</th>
                            </tr>
                          </thead>
                          <tbody>
                          <?php
						  foreach($history as $key => $data){?>
                            <tr>
                              <td><span class="text-muted"><?php echo ++$key;?></span></td>
                              <td><?php echo $data["total_numbers"];?></td>
                              <td>0<?php echo $data["start_number"];?></td>
                              <td>0<?php echo $data["end_number"];?></td>
                              <td><?php echo ucwords($data["first_name"] . " ".$data["last_name"]);?></td>
                              <td><?php echo $data["data_source_name"];?></td>
                              <td><?php echo date("d F, Y", strtotime($data["date_added"]));?></td>
                              <td><a href="/generate/history-detail/?token=<?php echo $data["token"];?>"><i class="fe fe-external-link" data-toggle="tooltip" title="" data-original-title="fe fe-external-link"></i></a></td>
                            </tr>
                          <?php }?>
                          </tbody>
                        <?php }else{?>
                        <tr>
                        	<td>No Records Found!</td>
                        </tr>
                        <?php }?>
                        </table>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
          </div>
      </div>